# Generated by Django 4.2.15 on 2024-09-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0031_claim_care_type_claim_refer_from_claim_refer_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_column='ClaimCode', max_length=50)),
            ],
        ),
    ]
